## Cada push en main ejecuta la pipeline.
trigger:
- main

pool:
## Azure crea una máquina Linux temporal
## para ejecutar la pipeline.
  name: Default
  demands:
  - Agent.Name -equals Bicep-Agent

variables:
  resourceGroup: 'Bicep1'

stages:

- stage: Validate

  jobs:

  - job: ValidateBicep

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-Connection-Bicep1'
        scriptType: ps
        scriptLocation: inlineScript

        inlineScript: |
          az deployment group validate --resource-group $(resourceGroup) --template-file main.bicep --parameters parameters.json

# Agregar What-If
- stage: WhatIf

  dependsOn: Validate

  jobs:

  - job: WhatIf

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure-Connection-Bicep1'
        scriptType: ps
        scriptLocation: inlineScript

        inlineScript: |
          az deployment group what-if --resource-group $(resourceGroup) --template-file main.bicep --parameters parameters.json            

## Agregar Deployment
##  stage: Deploy
##
##   dependsOn: WhatIf
##
##   jobs:
##
##   - job: DeployResources
##
##     steps:
##
##     - task: AzureCLI@2
##       inputs:
##         azureSubscription: 'Azure-Connection-Bicep1'
##         scriptType: ps
##        scriptLocation: inlineScript
##
##         inlineScript: |
##           az deployment group create --resource-group $(resourceGroup) --template-file main.bicep --parameters parameters.json


