trigger:
- main

pool:
  name: Default

variables:
  resourceGroup: 'Bicep1'

stages:

# ==========================
# VALIDATE
# ==========================

- stage: Validate
  displayName: 'Validate Bicep'

  jobs:

  - job: ValidateBicep

    steps:

    - task: AzureCLI@2
      displayName: 'Validate Deployment'

      inputs:
        azureSubscription: 'Azure-Connection-Bicep1'
        scriptType: ps
        scriptLocation: inlineScript

        inlineScript: |
          az deployment group validate --resource-group $(resourceGroup) --template-file main.bicep --parameters parameters.json

# ==========================
# WHATIF
# ==========================

- stage: WhatIf

  displayName: 'Preview Changes'

  dependsOn: Validate

  jobs:

  - job: WhatIf

    steps:

    - task: AzureCLI@2
      displayName: 'Run WhatIf'

      inputs:
        azureSubscription: 'Azure-Connection-Bicep1'
        scriptType: ps
        scriptLocation: inlineScript

        inlineScript: |
          az deployment group what-if --resource-group $(resourceGroup) --template-file main.bicep --parameters parameters.json

# ==========================
# DEPLOY
# ==========================

- stage: Deploy

  displayName: 'Deploy Resources'

  dependsOn: WhatIf

  jobs:

  - deployment: DeployResources

    environment: TrainingBiceps

    strategy:

      runOnce:

        deploy:

          steps:

          - task: AzureCLI@2
            displayName: 'Deploy Bicep'

            inputs:
              azureSubscription: 'Azure-Connection-Bicep1'
              scriptType: ps
              scriptLocation: inlineScript

              inlineScript: |
                az deployment group create --resource-group $(resourceGroup) --template-file main.bicep --parameters parameters.json

          - task: AzureCLI@2
            displayName: 'Show Outputs'

            inputs:
              azureSubscription: 'Azure-Connection-Bicep1'
              scriptType: ps
              scriptLocation: inlineScript

              inlineScript: |
                az deployment group show --resource-group $(resourceGroup) --name main --query properties.outputs